### ISSUE TITLE
Trouble with make in the Docker image provided

### ISSUE THREAD

**Issue by martinjm97** [pdlan/OSCAR#1]
Hi, 

I built the dependencies for the docker image that you provided, but when I run `make` in `/oscar/bin`, I get:
```
cd ../irlexer && go build && cp irlexer ../bin
main.go:14:2: cannot find package "github.com/ianlancetaylor/demangle" in any of:
	/usr/lib/go-1.10/src/github.com/ianlancetaylor/demangle (from $GOROOT)
	/root/go/src/github.com/ianlancetaylor/demangle (from $GOPATH)
main.go:15:2: cannot find package "github.com/llir/ll" in any of:
	/usr/lib/go-1.10/src/github.com/llir/ll (from $GOROOT)
	/root/go/src/github.com/llir/ll (from $GOPATH)
Makefile:5: recipe for target 'irlexer' failed
make: *** [irlexer] Error 1
```

Best, 
Jesse

**Comment by martinjm97** [comment]
I updated to the latest version of go to `1.16` in the docker image and then ran `go mod tidy` in the `irlexer` directory. Running `make` succeeds.

**Comment by martinjm97** [comment]
Update: Even with new dependencies, I still can't run OSCAR without errors.

**Comment by pdlan** [comment]
Did you update to the latest commit?

**Comment by martinjm97** [comment]
Hi, 

Thanks for checking in. With the latest code, I get the following error:

```
./scripts/pretrain.sh 
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    with open('README.md') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from fairseq import checkpoint_utils, distributed_utils, options, progress_bar, tasks, utils
  File "/oscar/OSCAR/model/fairseq/__init__.py", line 9, in <module>
    import fairseq.criterions  # noqa
  File "/oscar/OSCAR/model/fairseq/criterions/__init__.py", line 24, in <module>
    importlib.import_module('fairseq.criterions.' + module)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/oscar/OSCAR/model/fairseq/criterions/adaptive_loss.py", line 10, in <module>
    from fairseq import utils
  File "/oscar/OSCAR/model/fairseq/utils.py", line 20, in <module>
    from fairseq.modules import gelu, gelu_accurate
  File "/oscar/OSCAR/model/fairseq/modules/__init__.py", line 28, in <module>
    from .irexp_transformer_sentence_encoder import IRTransformerSentenceEncoderNoMiddleLayers
ModuleNotFoundError: No module named 'fairseq.modules.irexp_transformer_sentence_encoder'
```
It seems that the version of fairseq in your repo does not have all of the files that it should have.

**Comment by pdlan** [comment]
Seems that the code is not updated. This error should have been fixed in #2 and #3. Can you try to have a clean start with the latest commit? You may still need to check the version of Go by the way.

**Comment by martinjm97** [comment]
Thanks for the reference, I'll comment that import statement out. Likewise for `IRBlockDataset` in `model/fairseq/tasks/poj_similarity.py`? Update: that broke downstream code.

**Comment by pdlan** [comment]
You don't need to do so. I have fixed these problems in the recent commit.

**Comment by pdlan** [comment]
In commit 8a33a99b72181ee6bbdeb06f6723e950141d000a I removed several imports of the missing experimental code. And in later commits I fixed other bugs.

**Comment by martinjm97** [comment]
Oh that's totally my bad. I had multiple versions of the repo and looked at the wrong one. On the latest version I get:
```
  File "train.py", line 350, in <module>
    cli_main()
  File "train.py", line 346, in cli_main
    main(args)
  File "train.py", line 48, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=0)
  File "/oscar/OSCAR/model/fairseq/tasks/ir_masked_lm.py", line 119, in load_dataset
    raise FileNotFoundError('Dataset not found: {} ({})'.format(split, split_path))
NameError: name 'split_path' is not defined
```

I think this is a bug in an error message that arises as a result of some data missing from the `pretrain` folder (downloaded from the OneDrive link) such as `imagemagick`, `linux-vmlinux`, etc.

**Comment by pdlan** [comment]
Did you process the pretrain data with the script? Does the directory /oscar/data-bin/pretrain exist?

**Comment by martinjm97** [comment]
Yes, it exists and contains: `0  10  12  14  16  18  2  4  6  8  inst_dict.txt 1  11  13  15  17  19  3  5  7  9  state_dict.txt`.

**Comment by pdlan** [comment]
Can you print the directory tree of /oscar/data-bin/pretrain? It seems that some files are missing.

**Comment by martinjm97** [comment]
I realized that there was some issue with extracting the data. I started from-scratch and it looks like all of the folders that are supposed to be there are there. Thanks again for the help. I'll keep you posted.

**Comment by martinjm97** [comment]
Also, there's a missing dependency `uuidgen`, which can be added with `apt-get install uuid-runtime`.

**Comment by martinjm97** [comment]
With the updated data, I still get the same error. My tree is:
```
├── 0
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 1
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 10
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 11
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 12
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 13
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 14
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 15
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 16
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 17
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 18
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 19
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 2
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 3
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 4
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 5
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 6
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 7
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 8
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── 9
│   ├── insts
│   │   └── dict.txt
│   ├── pos
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   └── states
│       ├── dict.txt
│       ├── train.bin
│       └── train.idx
├── inst_dict.txt
└── state_dict.txt
```

**Comment by pdlan** [comment]
That's my bad. I forgot that the default shm size of docker is too small for the processing. You can run the docker with `
sudo nvidia-docker run -it --shm-size=100g --mount type=bind,source="$(pwd)",target=/oscar oscar:latest`. If you still cannot process the data succesfully you may download the [proccessed data](https://1drv.ms/u/s!AjYwgux2zLgMiAqS__PLGiGgofFM?e=Q586Mb).

**Comment by martinjm97** [comment]
The new docker command still didn't allow me to preprocess the data, however, the processed data did allow me to run the pretraining script. Thank you for adding that!

**Comment by martinjm97** [comment]
How long should pretraining take? It stopped producing output after about half an hour.

**Comment by pdlan** [comment]
How much vram does your GPU have? Seems that OOM happened. It should at least take several days to pretrain with 8 GPUs.

**Comment by pdlan** [comment]
And can you attach the log here?

**Comment by pdlan** [comment]
Also, the log interval is 1000 so you may need to wait for the first line of log even if everything is OK. :)

**Comment by martinjm97** [comment]
I see. I was training on an instance with a single GPU. I can scale up easily, but I'll first go back and think over my evaluation methodology. After that, I might send a follow up email your way. Thanks again!
