### ISSUE TITLE
Error while pretraining

### ISSUE THREAD

**Issue by thdusdl1219** [pdlan/OSCAR#2]
Hi! Thanks for open-sourcing your great work.
I'd like to use OSCAR for embedding binary, but I couldn't find the pre-trained BERT model so I was pre-training it by myself with provided scripts. 
So, I executed `OSCAR/process-pretrain-data/process.sh` in the given docker and faced the below error msg. 
It seems the `irexp_transformer_sentence_encoder` file is missing under fairseq/modules directory.
Could you help to resolve this? Thanks!

```
Traceback (most recent call last):
  File "preprocess.py", line 13, in <module>
    from fairseq import options, tasks, utils
  File "/oscar/model/fairseq/__init__.py", line 9, in <module>
    import fairseq.criterions  # noqa
  File "/oscar/model/fairseq/criterions/__init__.py", line 24, in <module>
    importlib.import_module('fairseq.criterions.' + module)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/oscar/model/fairseq/criterions/sentence_ranking.py", line 11, in <module>
    from fairseq import utils
  File "/oscar/model/fairseq/utils.py", line 20, in <module>
    from fairseq.modules import gelu, gelu_accurate
  File "/oscar/model/fairseq/modules/__init__.py", line 28, in <module>
    from .irexp_transformer_sentence_encoder import IRTransformerSentenceEncoderNoMiddleLayers
ModuleNotFoundError: No module named 'fairseq.modules.irexp_transformer_sentence_encoder'
```

**Comment by pdlan** [comment]
It seems that we forgot to clean some experimental code. You could try to comment this import statement. Sorry for the inconvenience.

**Comment by thdusdl1219** [comment]
Okay, lemme try. Thank you!
