### ISSUE TITLE
another error while training

### ISSUE THREAD

**Issue by thdusdl1219** [pdlan/OSCAR#3]
Hi I'm doing pretrain with given scripts and faced below error while executing `./model/scripts/pretrain.sh`.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/oscar/model/train.py", line 309, in distributed_main
    main(args, init_distributed=True)
  File "/oscar/model/train.py", line 51, in main
    model = task.build_model(args)
  File "/oscar/model/fairseq/tasks/ir_masked_lm.py", line 210, in build_model
    model = models.build_model(args, self)
  File "/oscar/model/fairseq/models/__init__.py", line 45, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/oscar/model/fairseq/models/irbert/model.py", line 86, in build_model
    encoder = IRBertEncoder(args, task.instruction_dictionary, task.state_dictionary)
  File "/oscar/model/fairseq/models/irbert/model.py", line 263, in __init__
    copy_weights(self.sentence_encoder, self.sentence_encoder_momentum)
NameError: name 'copy_weights' is not defined
```

copy_weights function seems missing in this repository.

**Comment by pdlan** [comment]
Fixed

**Comment by thdusdl1219** [comment]
It looks working. Thank you!
